### ISSUE TITLE
我想知道您是如何给DeskBand   debug的？

### ISSUE THREAD

**Issue by xyfll7** [20154530/DeskBandTest#1]
我最近也在研究DeskBand
但是我不知道该如何debug它
每次都要将dll注册到Shell中运行起来，但是这样就没法debug了
您是如何做到的？

**Comment by Y-Theta** [comment]
@xyfll7 
只能通过输出log来看了，原先那个库就是有一堆用于生成log文件的东西，我把那些删了，因为我用到的功能有限，所以就没加那个

**Comment by xyfll7** [comment]
嗯嗯，后来我还发现能把 CSDeskband当作一个普通的控件加载到普通窗口中，debug也比较方便。
还有，可以监听全局未捕获错误。

**Comment by Y-Theta** [comment]
@xyfll7 
我还真没试过直接引用这个dll，不过应该要比看log好用。
对了，你知不知道360或者电脑管家那个输入法旁边的那种嵌入式窗口是什么类型
![](https://imgsa.baidu.com/exp/pic/item/9a1151c2d56285350bec97a99bef76c6a6ef63ef.jpg)

**Comment by xyfll7** [comment]
360厉害，我并不知。

**Comment by oldfish96** [comment]
net4.5想使用的话咋办?

**Comment by Y-Theta** [comment]
> net4.5想使用的话咋办?

这个没试过，当初主要在win10用就直接4.7了 还有win11上已经不支持这种交互了
